// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJqhQSOl9KBiazEAduxH4hnr1MBgjS424',
    appId: '1:609673331471:web:4c99caef5f74e6a60eb47a',
    messagingSenderId: '609673331471',
    projectId: 'let-us-chat-841c7',
    authDomain: 'let-us-chat-841c7.firebaseapp.com',
    databaseURL: 'https://let-us-chat-841c7-default-rtdb.firebaseio.com',
    storageBucket: 'let-us-chat-841c7.appspot.com',
    measurementId: 'G-K2W1T8VK70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqlX24PLlBLFiwCOeoXL3RHJpXIDMffks',
    appId: '1:609673331471:android:27a40b392d8a84f80eb47a',
    messagingSenderId: '609673331471',
    projectId: 'let-us-chat-841c7',
    databaseURL: 'https://let-us-chat-841c7-default-rtdb.firebaseio.com',
    storageBucket: 'let-us-chat-841c7.appspot.com',
  );
}
